services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rag-app
    ports:
      - "8500:8500"
    volumes:
      - model_cache:/root/.cache
      - ../data:/app/data
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      - PYTHONPATH=/app

volumes:
  model_cache: